---
- name: Install NetBox
  hosts: localhost
  connection: local
  become: true  # This is needed since NetBox installation requires root privileges
  vars:
    netbox_python_binary: /root/.pyenv/shims/python3.8
  roles:
    - { role: . }  # The dot indicates the current directory as the role
